name: mac

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-15 ]
    name: mac
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          brew install automake boost catch2 cereal gfortran \
            libelf libomp libtool llvm open-mpi yaml-cpp
#      - name: spack
#        run: bash scripts/ci/install_deps.sh
      - name: test
        run: |
          export BREW_PREFIX=$(brew --prefix)
          export OpenMP_ROOT=$BREW_PREFIX/opt/libomp
          export PATH="$BREW_PREFIX/opt/llvm/bin:$PATH"
          export LDFLAGS="-L$BREW_PREFIX/opt/llvm/lib -L$BREW_PREFIX/opt/libomp/lib"
          export CPPFLAGS="-I$BREW_PREFIX/opt/llvm/include -I$BREW_PREFIX/opt/libomp/include"
          export DYLD_LIBRARY_PATH="$BREW_PREFIX/opt/libomp/lib:$DYLD_LIBRARY_PATH"
          export OpenMP_C_FLAGS="-Xclang -fopenmp"
          export OpenMP_C_LIB_NAMES="omp"
          export OpenMP_C_INCLUDE_DIR="$BREW_PREFIX/opt/libomp/include"
          export OpenMP_C_LIBRARY_DIR="$BREW_PREFIX/opt/libomp/lib"
          export OpenMP_CXX_FLAG="-Xclang -fopenmp"
          export OpenMP_CXX_INCLUDE_DIR="$BREW_PREFIX/opt/libomp/include"
          export OpenMP_CXX_LIB_NAMES="libomp"
          mkdir build
          cd build
          cmake -DOpenMP_CXX_FLAG="-Xclang -fopenmp" -DOpenMP_CXX_INCLUDE_DIR=$BREW_PREFIX/opt/libomp/include -DOpenMP_CXX_LIB_NAMES=libomp -DOpenMP_C_FLAG="-Xclang -fopenmp" -DOpenMP_C_INCLUDE_DIR=$BREW_PREFIX/opt/libomp/include -DOpenMP_C_LIB_NAMES=libomp -DOpenMP_libomp_LIBRARY=$BREW_PREFIX/opt/libomp/lib/libomp.dylib -DSITE:STRING="mac-15" -DHSHM_ENABLE_PROCFS_SYSINFO:BOOL=ON ..
          ctest -T Build
          sudo make install 
          ctest -D Experimental
