name: win 2025

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          vcpkg install
      - name: test
        run: |
          vcpkg integrate install
          del vcpkg.json
          dir "c:/vcpkg/packages/pkgconf_x64-windows/"
          dir "c:/vcpkg/packages/pkgconf_x64-windows/bin"
          dir "c:/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf"
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="win-25" -DPKG_CONFIG_EXECUTABLE="C:/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe" -DCatch2_DIR="C:/vcpkg/packages/catch2_x64-windows" -DCMAKE_PREFIX_PATH="C:/vcpkg/packages" ..
          ctest -C Release -D Experimental
        shell: cmd